-- Backfill region_code and region_display_name on existing crawl_boards rows
-- Generated by Cascade assistant on 2025-02-03
--
-- 사용 가이드
-- 1) 아래 패턴 매칭 규칙을 실제 운영 데이터에 맞게 점검/보완하세요.
--    - 기본적으로 게시판 이름/카테고리/URL에 포함된 문자열로 광역 단위를 추론합니다.
--    - 매칭되지 않는 행은 마지막 섹션의 검증 쿼리로 확인 후 수동 업데이트를 진행하세요.
-- 2) 트랜잭션 내에서 수행되므로, 의도치 않은 매핑이 있으면 ROLLBACK 하세요.
-- 3) 모든 업데이트가 정상이라면 COMMIT 을 실행합니다.
--
-- 참고: regions 테이블은 17개 광역단체가 시드로 채워져 있다고 가정합니다.

BEGIN;

WITH region_map AS (
  SELECT *
  FROM (
    VALUES
      ('KR-11', '서울특별시', ARRAY['서울', 'seoul']),
      ('KR-26', '부산광역시', ARRAY['부산', 'busan']),
      ('KR-27', '대구광역시', ARRAY['대구', 'daegu']),
      ('KR-28', '인천광역시', ARRAY['인천', 'incheon']),
      ('KR-29', '광주광역시', ARRAY['광주', 'gwangju']),
      ('KR-30', '대전광역시', ARRAY['대전', 'daejeon']),
      ('KR-31', '울산광역시', ARRAY['울산', 'ulsan']),
      ('KR-50', '세종특별자치시', ARRAY['세종', 'sejong']),
      ('KR-41', '경기도', ARRAY['경기', 'gyeonggi', 'gyeonggi-do']),
      ('KR-42', '강원특별자치도', ARRAY['강원', 'gangwon']),
      ('KR-43', '충청북도', ARRAY['충북', 'chungbuk', 'chungcheongbuk']),
      ('KR-44', '충청남도', ARRAY['충남', 'chungnam', 'chungcheongnam']),
      ('KR-45', '전북특별자치도', ARRAY['전북', 'jeonbuk']),
      ('KR-46', '전라남도', ARRAY['전남', 'jeonnam']),
      ('KR-47', '경상북도', ARRAY['경북', 'gyeongbuk']),
      ('KR-48', '경상남도', ARRAY['경남', 'gyeongnam']),
      ('KR-49', '제주특별자치도', ARRAY['제주', 'jeju'])
  ) AS t(code, name_kr, patterns)
),
source_rows AS (
  SELECT
    cb.id,
    rm.code,
    rm.name_kr,
    ROW_NUMBER() OVER (PARTITION BY cb.id ORDER BY rm.code) AS pattern_rank
  FROM crawl_boards cb
  JOIN region_map rm
    ON (
      EXISTS (
        SELECT 1
        FROM unnest(rm.patterns) pattern
        WHERE
          (cb.name IS NOT NULL AND cb.name ILIKE CONCAT('%', pattern, '%'))
          OR (cb.category IS NOT NULL AND cb.category ILIKE CONCAT('%', pattern, '%'))
          OR (cb.board_url IS NOT NULL AND cb.board_url ILIKE CONCAT('%', pattern, '%'))
      )
    )
  WHERE cb.region_code IS NULL
)
UPDATE crawl_boards AS cb
SET
  region_code = src.code,
  region_display_name = COALESCE(cb.region_display_name, src.name_kr)
FROM source_rows AS src
WHERE cb.id = src.id
  AND src.pattern_rank = 1;

-- 검증: 여전히 region_code 가 비어 있는 행과, 방금 업데이트된 행 확인

-- 1) 매핑되지 않은 레코드 확인
SELECT id, name, category, board_url
FROM crawl_boards
WHERE region_code IS NULL
ORDER BY created_at DESC;

-- 2) 이번 스크립트로 변경된 레코드 검수 (최근 변경 + 지역 정보)
SELECT id, name, region_code, region_display_name, updated_at
FROM crawl_boards
WHERE updated_at > NOW() - INTERVAL '5 minutes'
ORDER BY updated_at DESC;

-- 검수가 끝나면 COMMIT, 문제 발견 시 ROLLBACK
-- COMMIT;
-- ROLLBACK;
