import { Card, JobPostingCard, TalentCard } from '@/types';

export const aiRecommendations: Card[] = [
  {
    id: 'rec-1',
    type: 'job',
    isUrgent: true,
    organization: '수원 OO초등학교',
    title: '대체교사 긴급 모집',
    tags: ['초등전학년'],
    location: '수원',
    compensation: '시급 35,000원',
    deadline: '~ 10.17',
    daysLeft: 1,
  },
  {
    id: 'rec-2',
    type: 'job',
    organization: '용인 XX중학교',
    title: '코딩 방과후 강사',
    tags: ['파이썬', 'AI'],
    location: '용인',
    compensation: '시급 30,000원',
    deadline: '~ 10.25',
  },
  {
    id: 'rec-3',
    type: 'talent',
    isVerified: true,
    name: '김OO 강사',
    specialty: '초등 과학실험 전문',
    tags: ['STEAM', '영재교육'],
    location: '수원/용인/화성',
    experience: '경력 8년',
    rating: 4.9,
    reviewCount: 23,
  },
  {
    id: 'rec-4',
    type: 'job',
    organization: '성남 △△초등학교',
    title: '영어 원어민 보조',
    tags: ['회화', 'TEE'],
    location: '성남',
    compensation: '시급 40,000원',
    deadline: '~ 11.05',
  },
];

export const mainCards: Card[] = [
  {
    id: 'card-1',
    type: 'job',
    organization: '수원 OO초등학교',
    title: '코딩 방과후 강사 모집',
    tags: ['파이썬', '스크래치', '초등'],
    location: '수원 영통구',
    compensation: '시급 30,000원',
    deadline: '~ 10.25',
    daysLeft: 9,
  },
  {
    id: 'card-2',
    type: 'talent',
    isVerified: true,
    name: '이OO 강사님',
    specialty: '파이썬/AI 교육 전문',
    tags: ['파이썬', '머신러닝', '초등코딩', '중등코딩'],
    location: '수원/용인/화성',
    experience: '경력 6년',
    rating: 4.9,
    reviewCount: 18,
  },
  {
    id: 'card-3',
    type: 'job',
    organization: '용인 XX중학교',
    title: 'AI 코딩 교육 강사 모집',
    tags: ['인공지능', '파이썬', '중등'],
    location: '용인 수지구',
    compensation: '시급 35,000원',
    deadline: '~ 10.30',
    daysLeft: 14,
  },
  {
    id: 'card-4',
    type: 'talent',
    isVerified: false,
    name: '박OO 강사님',
    specialty: '영어 회화 전문',
    tags: ['원어민수준', '초등영어', 'TOEIC'],
    location: '수원/화성',
    experience: '경력 4년',
    rating: 4.7,
    reviewCount: 12,
  },
  {
    id: 'card-5',
    type: 'job',
    organization: '화성 ◇◇고등학교',
    title: '수학 방과후 강사',
    tags: ['고등수학', '수능대비'],
    location: '화성 동탄',
    compensation: '시급 45,000원',
    deadline: '~ 11.10',
    daysLeft: 25,
  },
  {
    id: 'card-6',
    type: 'talent',
    isVerified: true,
    name: '최OO 강사님',
    specialty: '과학실험 교육 전문',
    tags: ['물리', '화학', '실험'],
    location: '용인/성남',
    experience: '경력 10년',
    rating: 5.0,
    reviewCount: 31,
  },
  {
    id: 'card-7',
    type: 'job',
    isUrgent: true,
    organization: '성남 ☆☆초등학교',
    title: '체육 대체교사 긴급',
    tags: ['초등체육', '구기종목'],
    location: '성남 분당구',
    compensation: '일급 180,000원',
    deadline: '~ 10.18',
    daysLeft: 2,
  },
  {
    id: 'card-8',
    type: 'talent',
    isVerified: true,
    name: '정OO 강사님',
    specialty: '음악 교육 전문',
    tags: ['피아노', '바이올린', '합창'],
    location: '수원/용인',
    experience: '경력 7년',
    rating: 4.8,
    reviewCount: 15,
  },
  {
    id: 'card-9',
    type: 'job',
    organization: '안양 ◎◎중학교',
    title: '미술 방과후 강사',
    tags: ['회화', '디자인', '중등'],
    location: '안양 만안구',
    compensation: '시급 32,000원',
    deadline: '~ 11.01',
    daysLeft: 16,
  },
];
