create extension if not exists pg_trgm;
create extension if not exists unaccent;

create table if not exists public.search_logs (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  search_query text,
  tokens text[] default '{}',
  view_type text,
  filters jsonb,
  result_count integer,
  duration_ms integer,
  is_error boolean default false,
  error_message text
);

create index if not exists search_logs_created_at_idx on public.search_logs (created_at desc);

create index if not exists job_postings_title_trgm_idx on public.job_postings using gin (title gin_trgm_ops);
create index if not exists job_postings_org_trgm_idx on public.job_postings using gin (organization gin_trgm_ops);
create index if not exists job_postings_location_trgm_idx on public.job_postings using gin (location gin_trgm_ops);

create index if not exists talents_name_trgm_idx on public.talents using gin (name gin_trgm_ops);
create index if not exists talents_specialty_trgm_idx on public.talents using gin (specialty gin_trgm_ops);
