-- Adds regions reference table and region fields on crawl_boards
-- Generated by Cascade assistant on 2025-02-03

BEGIN;

CREATE TABLE IF NOT EXISTS public.regions (
  code TEXT PRIMARY KEY,
  name_kr TEXT NOT NULL,
  name_en TEXT,
  parent_code TEXT REFERENCES public.regions (code),
  depth SMALLINT NOT NULL DEFAULT 1,
  sort_order SMALLINT NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE OR REPLACE FUNCTION public.set_regions_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_regions_updated_at ON public.regions;
CREATE TRIGGER trg_regions_updated_at
BEFORE UPDATE ON public.regions
FOR EACH ROW
EXECUTE FUNCTION public.set_regions_updated_at();

-- Seed 17 metropolitan/provincial entries (depth = 1)
INSERT INTO public.regions (code, name_kr, name_en, parent_code, depth, sort_order)
VALUES
  ('KR-11', '서울특별시', 'Seoul Metropolitan City', NULL, 1, 10),
  ('KR-26', '부산광역시', 'Busan Metropolitan City', NULL, 1, 20),
  ('KR-27', '대구광역시', 'Daegu Metropolitan City', NULL, 1, 30),
  ('KR-28', '인천광역시', 'Incheon Metropolitan City', NULL, 1, 40),
  ('KR-29', '광주광역시', 'Gwangju Metropolitan City', NULL, 1, 50),
  ('KR-30', '대전광역시', 'Daejeon Metropolitan City', NULL, 1, 60),
  ('KR-31', '울산광역시', 'Ulsan Metropolitan City', NULL, 1, 70),
  ('KR-50', '세종특별자치시', 'Sejong Special Self-Governing City', NULL, 1, 80),
  ('KR-41', '경기도', 'Gyeonggi-do Province', NULL, 1, 90),
  ('KR-42', '강원특별자치도', 'Gangwon Special Self-Governing Province', NULL, 1, 100),
  ('KR-43', '충청북도', 'Chungcheongbuk-do Province', NULL, 1, 110),
  ('KR-44', '충청남도', 'Chungcheongnam-do Province', NULL, 1, 120),
  ('KR-45', '전북특별자치도', 'Jeonbuk Special Self-Governing Province', NULL, 1, 130),
  ('KR-46', '전라남도', 'Jeollanam-do Province', NULL, 1, 140),
  ('KR-47', '경상북도', 'Gyeongsangbuk-do Province', NULL, 1, 150),
  ('KR-48', '경상남도', 'Gyeongsangnam-do Province', NULL, 1, 160),
  ('KR-49', '제주특별자치도', 'Jeju Special Self-Governing Province', NULL, 1, 170)
ON CONFLICT (code) DO NOTHING;

ALTER TABLE public.crawl_boards
  ADD COLUMN IF NOT EXISTS region_code TEXT,
  ADD COLUMN IF NOT EXISTS subregion_code TEXT,
  ADD COLUMN IF NOT EXISTS region_display_name TEXT,
  ADD COLUMN IF NOT EXISTS school_level TEXT;

CREATE INDEX IF NOT EXISTS idx_crawl_boards_region_code ON public.crawl_boards (region_code);
CREATE INDEX IF NOT EXISTS idx_crawl_boards_subregion_code ON public.crawl_boards (subregion_code);

COMMIT;
