name: Generate Crawler with AI

on:
  repository_dispatch:
    types: [generate_crawler]
  workflow_dispatch:
    inputs:
      board_name:
        description: '게시판명'
        required: true
        type: string
      board_url:
        description: '게시판 URL'
        required: true
        type: string

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Install Playwright Chromium
        run: npx playwright install chromium --with-deps

      - name: Generate crawler with AI
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
          VITE_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY }}
          BOARD_NAME: ${{ github.event.client_payload.board_name || inputs.board_name }}
          BOARD_URL: ${{ github.event.client_payload.board_url || inputs.board_url }}
        run: |
          npx tsx scripts/generate-crawler-ai.ts "$BOARD_URL" "$BOARD_NAME"

      - name: Upload crawler code to DB
        env:
          VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
          VITE_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY }}
          BOARD_NAME: ${{ github.event.client_payload.board_name || inputs.board_name }}
        run: |
          npx tsx scripts/upload-crawler-to-db.ts "$BOARD_NAME"
